<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_aTableDynamicLocatorsLast</name>
   <tag></tag>
   <elementGuidId>231c29e7-4085-43af-b1cc-43f7de5ae709</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*//table//tr/td//a[text()='${buttonName}'])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
