<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tracuu_nhomHang</name>
   <tag></tag>
   <elementGuidId>dd9de430-9a1b-4f6f-90a2-cd498963947b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@id,'CcXX4zAk5yLXDt9f5o')]/following-sibling::span//span[contains(@class,'select2-selection__arrow')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
