<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>txt_username</description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>5c60c2d6-d76e-476b-ad5e-887b028ec764</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='passWord']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
