<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>txt_username</description>
   <name>input_username</name>
   <tag></tag>
   <elementGuidId>e4ef7b9a-ee39-47b3-b325-02c976e99db7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
