<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_idDynamicLocators</name>
   <tag></tag>
   <elementGuidId>ef604068-0d8e-4791-a991-8348005806e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table//input[@id='${idValue}']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
