<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_labelIndexDynamicLocators</name>
   <tag></tag>
   <elementGuidId>0cb90426-cb67-49b4-9ab9-f0ec96769545</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//label[contains(normalize-space(.),'${labelValue}')]/following-sibling::div[1]//input[@type='text'])[${index}]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
