<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_aTextDynamicLocators</name>
   <tag></tag>
   <elementGuidId>b1dffb15-efe0-4695-b53d-54b9dfd6c622</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*//a[normalize-space(text())='${tabValue}']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
